application: bms
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest